@startuml Mario State Machine

state SmallMario
state SuperMario
state CapeMario
state FireMario
state DeadMario

SmallMario --> CapeMario : Feather
SmallMario --> FireMario : FireFlower
SmallMario --> SuperMario : Mushroom

SuperMario --> SmallMario : Monster
SuperMario ----> CapeMario : Feather
SuperMario -> FireMario : FireFlower

CapeMario --> SmallMario : Monster
CapeMario --> FireMario : FireFlower
FireMario --> SmallMario : Monster
FireMario --> CapeMario : Feather

SmallMario --> SmallMario: Monster
SmallMario --> DeadMario : no more lifes
DeadMario --> [*]
[*] -r-> SmallMario

@enduml